// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4097.devilBotsSteamworks.commands;
import edu.wpi.cscore.UsbCamera;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.vision.VisionThread;
import grip.GripPipeline;

import org.opencv.core.Rect;
import org.opencv.imgproc.Imgproc;
import org.usfirst.frc4097.devilBotsSteamworks.Robot;

/**
 *
 */
public class placeGear extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	
	private static final int IMG_WIDTH = 320;
	private static final int IMG_HEIGHT = 240;
	
	private VisionThread visionThread;
	private double centerX = 0.0;
	private double width = 0.0;
	
	long cnt = 0;
	
	private final Object imgLock = new Object();
	
	
	

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public placeGear() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    	UsbCamera visionCamera = Robot.visionCamera;
    	
    	visionCamera.setResolution(IMG_WIDTH, IMG_HEIGHT);
        
        visionThread = new VisionThread(visionCamera, new GripPipeline(), pipeline -> {
            if (!pipeline.filterContoursOutput().isEmpty()) {
                Rect r = Imgproc.boundingRect(pipeline.filterContoursOutput().get(0));
                //Rect q = Imgproc.boundingRect(pipeline.filterContoursOutput().get(1));

                
                synchronized (imgLock) {
                    centerX = (r.x + (r.width / 2));
                    width = r.width;
                }
            }
        });
        visionThread.start();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double centerX;
        double width;
    	synchronized (imgLock) {
    		centerX = this.centerX;
    		width = this.width;
    		SmartDashboard.putNumber("Center of Target", centerX);
    		SmartDashboard.putNumber("Target Width", width);
    	}
    	double turn = centerX - (IMG_WIDTH / 2);
    	double drive = (width - 39)/39;
    	
    	double turnSpeed = Robot.map(turn,90,26,0.3,-0.3);
    	
    	for(int i = 50; i > 0; i--){
    		drive += (width - 39)/39;
    	}
    	drive /= 50;
    	drive /= 1.15;
    	
    	if(width < 35){
    		Robot.driveTrain.altDrive(-0.60f,-0.2);
    	}else{
    		Robot.driveTrain.altDrive(0, 0);
    	}
    	SmartDashboard.putNumber("Turn Distance", turn);
    	SmartDashboard.putNumber("Turn Speed", turnSpeed);
    	SmartDashboard.putNumber("Drive Speed", drive);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
