// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4097.devilBotsSteamworks.subsystems;

import org.usfirst.frc4097.devilBotsSteamworks.RobotMap;
import org.usfirst.frc4097.devilBotsSteamworks.commands.*;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class gearCatcher extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController gearMotor = RobotMap.gearCatchergearMotor;
    private final DigitalInput topSwitch = RobotMap.gearCatchertopSwitch;
    private final DigitalInput bottomSwitch = RobotMap.gearCatcherbottomSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void takeJoytickInput(Joystick main){
    	
    	SmartDashboard.putBoolean("Top Switch", topSwitch.get());
    	SmartDashboard.putBoolean("Bottom Switch",bottomSwitch.get());
    	
    	
    	if(main.getRawButton(1) && bottomSwitch.get()){
    		gearMotor.set(-0.25);
    	}
    	if(main.getRawButton(2) && topSwitch.get()){
    		gearMotor.set(0.25);
    	}
    	if(gearMotor.get() == 1 && !topSwitch.get()){
    		gearMotor.stopMotor();
    	}
    	if(gearMotor.get() == -1 && !bottomSwitch.get()){
    		gearMotor.stopMotor();
    	}
    	if(!main.getRawButton(1) && !main.getRawButton(2)){
    		gearMotor.stopMotor();
    	}
    }
    public void stop(){
    	gearMotor.stopMotor();
    }
    
    
    

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new controlGear());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

